global:
  scrape_interval: 15s
  external_labels:
    cluster: 'openshift-alpha'
    replica: '0'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

remote_write:
  - url: "http://prometheus-central:9090/api/v1/write"