global:
  scrape_interval: 15s
  external_labels:
    cluster: 'openshift-alpha'
    replica: '1'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

remote_write:
  - url: "http://victoria-metrics:8428/api/v1/write"